apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
spec:
  template:
    spec:
      containers:
        - name: n8n
          env:
            - name: QUEUE_BULL_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: prod-redis-secret
                  key: REDIS_PASSWORD
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n-worker
spec:
  template:
    spec:
      containers:
        - name: n8n-worker
          env:
            - name: QUEUE_BULL_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: prod-redis-secret
                  key: REDIS_PASSWORD
